# Generated by Django 5.2.7 on 2026-03-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
        ('Profile', '0007_studentprofile_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('promoted', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='Class.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='Profile.studentprofile')),
            ],
            options={
                'ordering': ['-academic_year'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
