# Generated by Django 5.2.7 on 2026-03-13 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject_teacher', '0001_initial'),
        ('Users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('period_number', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='Subject_teacher.teachingassignment')),
            ],
            options={
                'ordering': ['day', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='PeriodTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=30, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_timings', to='Users.school')),
            ],
            options={
                'ordering': ['period_number'],
                'unique_together': {('school', 'period_number')},
            },
        ),
    ]
