# Generated by Django 5.2.7 on 2026-02-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='tenant',
        ),
    ]
