# Generated by Django 5.2.7 on 2026-02-17 18:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_studentprofile_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id_proof',
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='student_document')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='Profile.studentprofile')),
            ],
        ),
    ]
