# Generated by Django 5.2.7 on 2026-02-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
        ('Profile', '0006_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Class.classroom'),
        ),
    ]
